### ISSUE TITLE
Responsive Design for Grid Page [in-progress]

### ISSUE THREAD

**Issue by ab-apps** [ab-apps/aryabota-ui#20]
The grid page looks like the below screenshot on larger screens. The left sidebar is not aligned with the AryaBota logo (it's wider) and ends with a little space on the bottom.
<img width="1673" alt="Screenshot 2021-10-04 at 12 51 44 PM" src="https://user-images.githubusercontent.com/91249224/135809664-dd33095f-56f2-46e2-a151-6873a4d6e561.png">

Add CSS such that it responsively resizes the sidebar and logo.
What we want it to look like:
![image](https://user-images.githubusercontent.com/91249224/135809722-610c5ed1-3ac1-4ca8-be85-4f7789dea99d.png)

**Comment by tnmyk** [comment]
I would like to work on this!

**Comment by tnmyk** [comment]
Can u please add hacktoberfest label on your repo or else these PRs wont count maybe.

**Comment by prernarao** [comment]
Hey @tnmyk ! Thanks for your PR. We'll take a look at get back to you :)

**Comment by prernarao** [comment]
@tnmyk PR looks good, will merge soon! Thanks again 🎉
