### ISSUE TITLE
Disable Run button while AryaBota is moving

### ISSUE THREAD

**Issue by ab-apps** [ab-apps/aryabota-ui#24]
While the bot is executing one set of commands, the Run button should be disabled so that there is no clash (could lead to unpredictable behaviour?).

**Comment by mihirterna** [comment]
Hi, I tried to run it locally, I am getting Internal Server error while registering on login page.
Request URL: https://aryabota.herokuapp.com/api/user

**Comment by mihirterna** [comment]
I would like to work on this issue, can you please assign it to me?

**Comment by ab-apps** [comment]
Hey @mihirterna the server error is fixed, but also we implemented some other changes to the Run button instead. Will be closing this issue, but you can take a look at any of the other open/unanswered ones instead.
